apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadnspo5398-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadnspo5398-tenant-component
    app.kubernetes.io/part-of: loadnspo5398-tenant-app
  name: loadnspo5398-tenant-component
  namespace: loadnspo5398-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadnspo5398-tenant-component
    weight: null
status: {}
